[package]
name = "firmware-common"
authors = ["Pegasis <me@pegasis.site>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-sync = { version = "0.1.0", features = [] }
bitvec = { version = "1.0.1", default-features = false }
bytecheck = { version = "0.6.9", default-features = false}
defmt = "0.3"
heapless = { version = "0.7.5", default-features = false}
micromath = { version = "2.0.0", default-features = false, features = ["vector"]}
rkyv = { version = "0.7.39", default-features = false, features = [
    "validation",
    "size_32",
    "alloc"
] }
