[package]
name = "firmware-common-ffi"
version = "0.1.3"
edition = "2021"

[dependencies]
firmware-common-new = { path = "../firmware-common-new", default-features = false, features = ["defmt"] }

[lib]
name = "firmware_common_ffi"
crate-type = ["staticlib"]
