[package]
name = "firmware-common-ffi"
version = "0.6.0"
edition = "2024"

[dependencies]
firmware-common-new = { path = "../firmware-common-new", default-features = false }

[lib]
name = "firmware_common_ffi"
crate-type = ["staticlib", "cdylib"]
