[package]
name = "firmware-common-ffi"
version = "0.1.1"
edition = "2021"

[dependencies]
embassy-sync = "0.6.2"
firmware-common-new = { path = "../firmware-common-new", default-features = false, features = ["defmt"] }

[lib]
name = "firmware_common_ffi"
crate-type = ["staticlib"]
